### ISSUE TITLE
Morning session Peer to peer code review

### ISSUE THREAD

**Issue by aliabbani** [TedLivist/awesome-books#4]
# The project is actually really good 💯 🥇 
Hello you have really done a great job but we think as a group reviewing your code you can still improve your project though : 
## add ⬆️ 

* When you add a new book. The new book should show first. Please make sure about this point. So keep in mind to use the unshift() not push(). or reverse() method.

Cheers and happy coding

**Comment by elmar8287** [comment]
Dear Ali,

Thanks for your comment. I will fix this ordering issue a.s.a.p.

My regards,

Elmar
